# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: my-personal-computer

variables:
- group: "my-variable-group"

steps:
- template: TryTemplate.yaml  # Template reference

- script: echo Hello, world!
- script: echo $(Group1)

  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

